# Generated by Django 3.0.8 on 2020-07-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certifications',
            options={'verbose_name_plural': 'Certifications'},
        ),
    ]
