# Generated by Django 3.0.8 on 2020-07-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200719_0853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certifications',
        ),
    ]
