# Generated by Django 3.0.8 on 2020-07-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0003_delete_certifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('title', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('duration', models.CharField(max_length=50)),
                ('provider', models.CharField(max_length=40)),
                ('score', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Certifications',
                'db_table': 'Certifications',
            },
        ),
    ]
