# Generated by Django 3.0.8 on 2020-07-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_certifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='score',
            field=models.FloatField(default=None, null=True),
        ),
    ]
