# Generated by Django 3.0.8 on 2020-07-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20200719_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProjects',
            fields=[
                ('title', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('duration', models.CharField(max_length=20, null=True)),
                ('team_size', models.IntegerField()),
                ('role', models.CharField(max_length=40)),
                ('tools_used', models.TextField()),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=150)),
                ('is_private', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'GroupProjects',
                'db_table': 'GroupProjects',
            },
        ),
        migrations.CreateModel(
            name='PersonalProjects',
            fields=[
                ('title', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('duration', models.CharField(max_length=20)),
                ('tools_used', models.TextField()),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=150)),
                ('is_private', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'PersonalProjects',
                'db_table': 'PersonalProjects',
            },
        ),
    ]
